### ISSUE TITLE
Delete Tag Functionality and List Tags Functionality 

### ISSUE THREAD

**Issue by aragostinho** [cal5barton/frontsharp#4]
I'm suggesting two new methods:     

- *Tag DeleteTag(string id)*;

- *ListResultResponseBody<Tag> ListTags()*;

I cloned the repo and implemented them, can I be a contributor?

**Comment by cal5barton** [comment]
@aragostinho yes you are more than welcome to contribute. If you want to put in a pull request I will gladly approve any changes.

**Comment by cal5barton** [comment]
@aragostinho please resolve the changes in the PR  so I can close this issue. Thanks!

**Comment by cal5barton** [comment]
The PR has been completed and changes have been deployed.
